volumes:
  angie_conf:

services:
  angie:
    image: angie
    container_name: angie
    ports:
      - "80:80"
    volumes:
      - angie_conf:/etc/angie/conf.d:ro
      - network_internal.conf:/etc/angie/network_internal.conf:ro

  dockergen:
    image: nginxproxy/docker-gen
    command: -notify-sighup angie -watch /etc/docker-gen/templates/angie.tmpl /etc/angie/conf.d/default.conf
    # the name "angie" passed to the "-notify-sighup" flag must exactly match the container name used for the angie container above.
    environment:
      # angie-proxy environment variable (HTTP_PORT etc.) must be set on the docker-gen container (not the angie container)
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./angie.tmpl:/etc/docker-gen/templates/angie.tmpl
      - angie_conf:/etc/angie/conf.d

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.example
